
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name : "ner_duckling"

path: "/media/hticdeep/drive3/shyam/IDAI/RASA/Gere_version2/models/nlu"
data: "/media/hticdeep/drive3/shyam/IDAI/RASA/Gere_version2/data/modified_data.json"

