
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
- name : "ner_duckling"

path: "/media/hticdeep/drive3/shyam/IDAI/RASA/Gere_version2/models/nlu"
data: "/media/hticdeep/drive3/shyam/IDAI/RASA/Gere_version2/data/modified_data.json"

